# Generated by Django 4.2.2 on 2023-07-03 05:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_product_category_product_isavailable_product_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='users',
            new_name='user',
        ),
    ]
