# Generated by Django 4.2.2 on 2023-07-04 17:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_rename_isavailable_product_is_available'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='is_available',
        ),
    ]
