# Generated by Django 4.2.2 on 2023-07-05 17:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('address', '0003_alter_address_city_alter_address_country_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='address',
            old_name='districk',
            new_name='district',
        ),
    ]
