# Generated by Django 4.2.2 on 2023-07-05 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('address', '0004_rename_districk_address_district'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='city',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='address',
            name='country',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='address',
            name='district',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='address',
            name='number',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='address',
            name='state',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='address',
            name='street',
            field=models.CharField(max_length=100),
        ),
    ]
