# Generated by Django 4.2.2 on 2023-07-07 16:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_rename_product_order_products'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='price',
        ),
    ]
