# Generated by Django 4.2.2 on 2023-07-11 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0004_order_seller'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('In_Progress', 'In Progress'), ('Delivered', 'Delivered'), ('Request_maid', 'Default')], default='Request_maid', max_length=50),
        ),
    ]
